# Generated by Django 3.2.7 on 2021-11-18 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ingresos', models.IntegerField(blank=True, null=True)),
                ('metaAhorro', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belvoid', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('type', models.CharField(max_length=100)),
                ('bankProductId', models.CharField(max_length=100)),
                ('accCategory', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('transactionDate', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
