# Generated by Django 3.2.7 on 2021-12-02 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintly_back', '0003_auto_20211202_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ingresos',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='link_id',
        ),
    ]
