# Generated by Django 3.2.7 on 2021-12-02 17:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fintly_back', '0004_auto_20211202_0941'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLinks',
            new_name='UserLink',
        ),
    ]
