# Generated by Django 3.2.7 on 2021-12-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintly_back', '0005_rename_userlinks_userlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlink',
            name='institution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
