# Generated by Django 3.2.7 on 2022-09-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintly_back', '0006_userlink_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transactions',
            field=models.BooleanField(default=False),
        ),
    ]
