# Generated by Django 3.2.7 on 2022-09-24 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintly_back', '0007_transaction_transactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transactions',
            new_name='transaction',
        ),
    ]
