# Generated by Django 3.2.7 on 2022-09-24 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintly_back', '0008_rename_transactions_transaction_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction',
            new_name='isTransaction',
        ),
    ]
